
# 话题配置
image_topic: ["/image_rect/compressed","/image_rect"]
lidar_topic: ["/lidar/livox_cloud1","/lidar/livox_cloud2","/lidar/livox_cloud3"]

# 录制性能配置
max_bag_duration: 1800   # bag包最大持续时间，单位秒

# 数据库清理配置
cleanup_interval: 28800    # 清理间隔(秒)，8小时
max_retention_days: 3      # 最大保留天数

